### ISSUE TITLE
Eclipse project doesn't build

### ISSUE THREAD

**Issue by nvnikolov** [DataCloud-project/DEF-PIPE-DSL#3]
- [ ] Xtext required but not in installation instructions
- [ ] Missing required artefacts from grammar cause build errors (missing valid grammar and instruction how to generate the required Xtext artifacts)
- [ ] Missing referred folders cause build errors
- [ ] Missing recommended Java JDK/JRE version (including in installation instructions)

**Comment by elvesater** [comment]
We suggest to refactor the whole Eclipse project. Maybe scrap the old Eclipse project and create a new Xtext Eclipse project  following the example https://gitlab.ow2.org/paasage/camel and then import the current Ecore model and reference it.
